### ISSUE TITLE
[suggestion] option to use pumpkins + blocks to create golems

### ISSUE THREAD

**Issue by xkforce** [MinecraftModDevelopment/Extra-Golems#18]
Ideally I'd like to craft these new golems the same way vanilla iron golems are so it would fit in better with packs that are meant to extend vanilla but still feel vanilla-ish.

**Comment by skyjay1** [comment]
That would have been my original plan, but in Minecraft you can only place pumpkins on solid opaque blocks. Some blocks, like glass and stained glass, don't count as "solid and opaque". I could add an option, but it complicates things because you then you would need a pumpkin for some golems but the special golem pumpkin for others.

**Comment by xkforce** [comment]
Here's a video demo of me spawning in the glass golem with a pumpkin placed on glass blocks arranged in a T shape:
https://www.twitch.tv/videos/367934691

And here's the json code for the Scavenge mod that made it work:
https://paste.ee/p/IeFh7

**Comment by TheGlitch76** [comment]
Okay, this proves it is possible. Adding a hard dependency is *extremely* unlikely, and Scavenge isn't free software so we can't look directly at the code and borrow from it. I will, however, do some research on methods to do so, and see if it's worth doing so (lag/coremodding).
There is also a chance skyjay (my 'boss') says "No." and this gets closed again.

**Comment by skyjay1** [comment]
Resolved and Released! Use Extra Golems 7.1.3

**Comment by xkforce** [comment]
Nice.  And you guys even added ore dictionary support too.
