### ISSUE TITLE
FastWorkbench compatibility

### ISSUE THREAD

**Issue by nickjackson-ff** [MinecraftModDevelopment/Extra-Golems#21]
I'm currently unable to create the Crafting Golem. I suspect this is because I have FastWorkbench installed, which replaces the crafting table. I believe the ID of the block is the same (`minecraft:crafting_table`).

Would it be possible to support oredict crafting tables? Such as:
- `workbench`
- `craftingTableWood`

Screenshots showing the issue (note the missing icon in the book):
![javaw_2019-02-13_18-04-36](https://user-images.githubusercontent.com/11531662/52752938-4f28b080-2fba-11e9-99be-5854298c1701.png)
![javaw_2019-02-13_18-05-52](https://user-images.githubusercontent.com/11531662/52752937-4f28b080-2fba-11e9-94d3-f503dc85b4b0.png)

**Comment by skyjay1** [comment]
I think I managed to enable OreDictionary checks for building golems... only to find out that FastWorkbench doesn't add their crafting table to OreDictionary at all. There goes that idea. So in order for this to work, I would have to change my whole golem-block registry to use String registry names instead of Blocks, which could have unintended side effects. I'll see what works and what doesn't. Thank you for letting me know!

**Comment by Shadows-of-Fire** [comment]
I'll go ahead and add the oredict entries, however I believe this would be better addressed by changing this map https://github.com/MinecraftModDevelopmentMods/Extra-Golems/blob/master-1.12/src/main/java/com/golems/util/GolemLookup.java#L38 to a
`private static final Map<IRegistryDelegate<Block>, Class<? extends GolemBase>> BLOCK_TO_GOLEM = new HashMap();` 
and doing the same for the map below it.  Storing Block objects instead of registry delegates causes unintended issues when registry overrides are in place, because those block objects are no longer valid to the game.

**Comment by skyjay1** [comment]
Thank you for that solution @Shadows-of-Fire , worked perfectly!
