### ISSUE TITLE
Redstone Golem turns path blocks into dirt blocks

### ISSUE THREAD

**Issue by NoveMax** [MinecraftModDevelopment/Extra-Golems#60]
Hello, love the mod. Quite simply, it seems the redstone block golem is turning my paths back into dirt blocks when walking on top of them. It doesn't seem to do this with any other golems that I've seen.

**Comment by skyjay1** [comment]
Yes, this is (slightly) intentional. It has to do with the way that the golem outputs redstone power - by placing and removing invisible blocks everywhere it goes. 
Back in March we fixed this problem with glowstone golems ( issue #49 ) by placing the invisible block one position higher, so it wasn't directly touching paths or farmland. If we did the same for redstone golems, it would only power blocks directly below it. To allow it to power adjacent redstone as well, I did not change anything for the redstone golem.
You can turn off the redstone power feature in the config under [golem_redstone]

**Comment by NoveMax** [comment]
> Yes, this is (slightly) intentional. It has to do with the way that the golem outputs redstone power - by placing and removing invisible blocks everywhere it goes.
> Back in March we fixed this problem with glowstone golems ( issue #49 ) by placing the invisible block one position higher, so it wasn't directly touching paths or farmland. If we did the same for redstone golems, it would only power blocks directly below it. To allow it to power adjacent redstone as well, I did not change anything for the redstone golem.
> You can turn off the redstone power feature in the config under [golem_redstone]

Thanks for the reply! I was actually assuming it had to do with it's ability to trigger power to redstone. I checked the config for the option to disable it, but it seems my config doesn't have the option to. 

![image](https://user-images.githubusercontent.com/73856936/98483914-d16af680-21d9-11eb-9fe8-e4852c13650e.png)

I should mention that I've edited the config before, as I play in a world with a couple friends and adjusted the power levels of the golems. I've only altered the health and attack values of golems though, so I haven't deleted any line of text (I don't believe so anyway....)

**Comment by skyjay1** [comment]
Ah, you're right. I removed the option to disable light / power at some point and forgot to add it back in. The option will be added in the next release.

**Comment by skyjay1** [comment]
Fixed (kinda) in release 11.1.9
